### ISSUE TITLE
[feature/old_member] 단원 등록 및 조회 기능 개발

### ISSUE THREAD

**Issue by AllyHyeseongKim** [cau-rubato/rubato-legacy-backend#1]
# 1. TODO
- [ ]  MemberController 생성
- [ ]  Member, ClubMember Entity 생성
- [ ]  단원 등록 데이터를 수렴하는 endpoint(임시저장, 최종제출)
- [ ]  단원 등록 데이터를 조회하는 endpoint
- [ ]  단원 데이터 생성, 조회하는 기능을 구현한 Service
- [ ]  단원 데이터 생성, 조회하는 Repository

---

# 2. Test Case
## 2.1. MemberControllerTest
- [ ]  단원 등록 데이터를 받아서 Service를 잘 호출하고 결과를 반환하는지 테스트
- [ ]  기존 단원 정보를 잘 조회하는지 테스트

## 2.2. MemberServiceTest
- [ ]  단원 등록 정보를 잘 저장하는지 테스트
- [ ]  실패 테스트

## 2.3. MemberRepositoryTest
- [ ]  데이터를 잘 조회하는지 테스트
- [ ]  데이터를 잘 저장하는지 테스트
- [ ]  실패 테스트

---

# 3. 유의사항
- _해당사항 없음_
