### ISSUE TITLE
[feature/key] 계정 생성을 위한 고유링크 생성 기능 개발

### ISSUE THREAD

**Issue by AllyHyeseongKim** [cau-rubato/rubato-legacy-backend#2]
# 1. TODO
- [ ]  KeyController 생성
- [ ]  Key Entity 생성
- [ ]  계정 생성을 위한 고유링크를 생성해서 제공(문자 발송 등)하는 endpoint
- [ ]  고유링크를 확인하는 endpoint
- [ ]  고유링크를 생성, 조회하는 기능을 구현한 Service
- [ ]  고유링크를 생성, 조회하는 Repository

---

# 2. Test Case
## 2.1. KeyControllerTest
- [ ]  등록된 단원 id를 받아서 Service를 잘 호출하고 결과를 반환하는지 테스트
- [ ]  고유링크 정보를 잘 확인하는지 테스트
## 2.2. KeyServiceTest
- [ ]  등록된 단원 id를 잘 확인하는지 테스트
- [ ]  고유링크 정보를 잘 저장하는지 테스트
- [ ]  고유링크 정보를 잘 확인하는지 테스트
- [ ]  실패 테스트
## 2.3. KeyRepositoryTest
- [ ]  데이터를 잘 조회하는지 테스트
- [ ]  데이터를 잘 저장하는지 테스트
- [ ]  실패 테스트

---

# 3. 유의사항
- _해당사항 없음_
